### ISSUE TITLE
PS4 wakes (to Welcome Back screen), but ps4-waker Error: Device didn't wake in time

### ISSUE THREAD

**Issue by mensa84** [dhleong/ps4-waker#64]
Hello,

I have a strange problem on Debian 9 and Node.js v8.9.1:
I was able to pair ps4-waker with my PS4 successful and also the command ps4-waker wakes my PS4, but around 30 seconds after the command was entered, the following error appears:

```
> WAKEUP sent to device... 192.168.1.33
> Error: Device didn't wake in time
>     at loop (/usr/lib/node_modules/ps4-waker/dist/waker.js:286:26)
>     at /usr/lib/node_modules/ps4-waker/dist/detector.js:141:9
>     at Detector.<anonymous> (/usr/lib/node_modules/ps4-waker/dist/detector.js:128:9)
>     at emitNone (events.js:106:13)
>     at Detector.emit (events.js:208:7)
>     at Detector.close (/usr/lib/node_modules/ps4-waker/dist/detector.js:87:10)
>     at ontimeout (timers.js:475:11)
>     at tryOnTimeout (timers.js:310:5)
>     at Timer.listOnTimeout (timers.js:270:5)
```

The PS4 did start. But: A few seconds after the ps4-waker errors did appear that blue screen is appearing at the PS4 (so approximately 35 seconds after the ps4-waker command was entered) which is saying "Welcome Back to PlayStation - Press the PS button to use the controller".
![grafik](https://user-images.githubusercontent.com/30125802/32893176-d46ac8ca-cad8-11e7-8070-8f6f5c6aa267.png)

Do you know, what is the problem?
When I start the PS4 by the App and or the Controller it does fully login into the normal menu, where you can select games and so on. Only ps4-waker seems to get a timeout or something like that.

So I tried to start by that command "ps4-waker --timeout 60" but this did not change anything. Maybe that parameter is for something else, cause the error message of ps4-waker appears again after around 30 seconds.

I did read about a similar problem here: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#error-device-didnt-wake-in-time
and here: https://github.com/dhleong/ps4-waker/issues/15
and tried that everything, but nothing helped.

I can bypass the blue welcome screen by just starting ps4-waker again, but that is no nice solution.

Could someone help me please?
Or is my PS4 just too slow for ps4-waker? Mine is from 2013.

**Comment by dhleong** [comment]
Those issues were actually for an unrelated issue—the PS4 did not wake up at all for them.

`--timeout` was not intended for that purposes, but I just published v1.4.2 that will let `--timeout` override how long it waits for the PS4 to wake up. Give that a try, and let me know if it fixes the problem for you!

**Comment by mensa84** [comment]
Hey, what a good timing! I did setup my new Debian VM a few minutes ago and installed ps4-waker and already got 1.4.2 :)

But I am sorry, it did not fix the problem :(
The "Error: Device didn't wake in time" still appears after around 30 seconds, although I have entered that command "ps4-waker --timeout 60".

Any other plan?

**Comment by dhleong** [comment]
`--timeout` is in milliseconds. Try `--timeout 60000` instead

**Comment by mensa84** [comment]
Thank you sooo much for that quick help, now it is working perfectly!!
Maybe you think about raising the default timeout a little bit? Or is really only my PS4 so much slower than others?

BTW: Do you have any idea, if on can turn of the orange stand-by LED of the PS4?

Thanks again!!

**Comment by dhleong** [comment]
Glad to hear!

You're the first to post about it. It's tricky to balance a timeout that's consistently long enough for most users, but which won't make you wait too long to discover that it didn't work.

>  can turn of the orange stand-by LED of the PS4?

Nope, that's hardware that I have nothing to do with.

**Comment by Mathy5** [comment]
Hi, i have some similar problem, when i proped:  

`sudo ps4-waker` ps4-waker can connect to my ps4 but on the screen appears a little icon that says that the app "PS4-waker" is connected but after 5 seconds the same things tells me it is disconnected and i can't even test it on my raspberry.

what is my mistake?

**Comment by dhleong** [comment]
It sounds like it is working as expected. If the PS4 is already awake,
`ps4-waker` with no arguments does nothing. What were you hoping it would
do?
